export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_DONE  = 'FETCH_POSTS_DONE';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const FETCH_POST_BY_ID_START = 'FETCH_POST_BY_ID_START';
export const FETCH_POST_BY_ID_DONE  = 'FETCH_POST_BY_ID_DONE';
export const FETCH_POST_BY_ID_ERROR = 'FETCH_POST_BY_ID_ERROR';

export const FETCH_CATEGORIES_DONE  = 'FETCH_CATEGORIES_DONE';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';

export const FETCH_POST_BY_CATEGORY_DONE  = 'FETCH_POST_BY_CATEGORY_DONE';
export const FETCH_POST_BY_CATEGORY_ERROR = 'FETCH_POST_BY_CATEGORY_ERROR';

export const ADD_POSTS_DONE  = 'ADD_POSTS_DONE';
export const ADD_POSTS_ERROR = 'ADD_POSTS_ERROR';

export const EDIT_POSTS_DONE = 'EDIT_POSTS_DONE';
export const EDIT_POSTS_ERROR = 'EDIT_POSTS_ERROR';

export const SET_SORT_METHOD = 'SET_SORT_METHOD';
