export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_DONE = 'FETCH_POSTS_DONE';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const ADD_POSTS_DONE = 'ADD_POSTS_DONE';
export const ADD_POSTS_ERROR = 'ADD_POSTS_ERROR';
